In [3]:
import numpy as np

In [4]:
vetor = [1,5,9]

In [6]:
type(vetor)

list

In [7]:
meuvetor = np.array(vetor)

In [9]:
type(meuvetor)

numpy.ndarray

In [15]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])